# Generated by Django 4.0.6 on 2022-08-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wehireapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='postjob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jobtitle', models.CharField(max_length=30)),
                ('companyname', models.CharField(max_length=30)),
                ('jobdescription', models.CharField(max_length=255)),
                ('Experience', models.CharField(choices=[('0-1', '0-1'), ('1-2', '1-2'), ('2-3', '2-3'), ('3-4', '3-4'), ('4-5', '4-5')], max_length=30)),
                ('workplace', models.CharField(choices=[('Hybrid', 'Hybrid'), ('Remote', 'Remote')], max_length=30)),
                ('Employmenttype', models.CharField(choices=[('Part Time', 'Part Time'), ('Full Time', 'Full Time')], max_length=30)),
            ],
        ),
    ]
