# Generated by Django 4.0.6 on 2022-08-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wehireapp', '0004_employeemodel_delete_userprofileinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='apply_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('resume', models.FileField(upload_to='wehireapp/static')),
                ('current_position', models.CharField(default='', max_length=100)),
                ('current_company', models.CharField(default='', max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('job_title', models.CharField(default='', max_length=50)),
                ('company_name', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
